Desafio/force-app/main/default/objects/Cotacao__c/Cotacao__c.object-meta.xml
<CustomObject>
    <label>Cotação</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desafio/force-app/main/default/objects/Cotacao__c/fields/Nome_do_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

Desafio/force-app/main/default/objects/Cotacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Produto__c</referenceTo>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

Desafio/force-app/main/default/objects/Cotacao__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Desafio/force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desafio/force-app/main/default/objects/Produto__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Cotacao__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Desafio/force-app/main/default/objects/Produto__c/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>Desconto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Desafio/force-app/main/default/objects/Produto__c/fields/Margem_de_Lucro__c.field-meta.xml
<CustomField>
    <fullName>Margem_de_Lucro__c</fullName>
    <label>Margem de Lucro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Desafio/force-app/main/default/objects/Produto__c/fields/Porcentagem_de_Imposto__c.field-meta.xml
<CustomField>
    <fullName>Porcentagem_de_Imposto__c</fullName>
    <label>Porcentagem de Imposto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Desafio/force-app/main/default/objects/Produto__c/fields/Valor_Final__c.field-meta.xml
<CustomField>
    <fullName>Valor_Final__c</fullName>
    <formula>(((Valor_Unitario__c * Quantidade__c) +
((Valor_Unitario__c * Quantidade__c) *  Porcentagem_de_Imposto__c ) + (( (Valor_Unitario__c * Quantidade__c) + (Valor_Unitario__c * Quantidade__c) *  Porcentagem_de_Imposto__c ) *  Margem_de_Lucro__c)  )) * (1 -  Desconto__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Desafio/force-app/main/default/classes/GerarCotacaoController.cls
public class GerarCotacaoController {
    public Cotacao__c currentQuotation { get; set; }
    public List<Produto__c> productList { get; set; }
    public GerarCotacaoController() {
        // Get Id 
        String cotacaoId = ApexPages.currentPage().getParameters().get('recordId');

  
        if (cotacaoId != null) {
            // recuperar dados da cotação__c
            currentQuotation = [SELECT Id, Name, Valor_Total__c, Nome_do_Cliente__r.Name FROM Cotacao__c WHERE Id = :cotacaoId LIMIT 1];

            // Recuperar dados produto__c
            if (currentQuotation != null) {
                productList = [
                    SELECT Id, Name, Desconto__c, Descricao__c, Margem_de_Lucro__c, Porcentagem_de_Imposto__c, 
                    Quantidade__c, Valor_Final__c, Valor_Unitario__c,Cotacao__r.Nome_do_Cliente__c,
                           Cotacao__r.Name, Cotacao__r.Valor_Total__c
                    FROM Produto__c 
                    WHERE Cotacao__c = :currentQuotation.Id
                ];
            } else {
                productList = new List<Produto__c>();
            }
        }
    }

    public List<Produto__c> getProductList() {
        return productList;
    }
}